version: '3.8'

services:
  mysqldb:
    container_name: mysqldb
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    env_file: ./.env
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: $MYSQL_DATABASE
    ports:
      - "3306:3306"
    volumes: 
      - db-config:/etc/mysql
      - db-data:/var/lib/mysql
      - ./db/backup/files/:/data_backup/data
    restart: always
    
  app:
    container_name: omulingo-app
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    image: omulingo-app
    env_file: ./.env
    ports:
      - "8000:3000"
    volumes:
      - ./:/app
    depends_on:
      - mysqldb
    stdin_open: true
    tty: true
    restart: on-failure

volumes: 
  db-config:
  db-data: